const PRODUCTS = {
  hydrating:{id:'hydrating',name:'Hydrating Serum',code:'HYDRA-CERA COMPLEX™ 22.91%',benefit:'Deep hydration + barrier support',desc:'A hydration-focused serum built around the HYDRA-CERA COMPLEX™ concept, featuring hyaluronic acid, ceramides and trehalose.',image:'assets/hydrating-real.jpg',gallery:['assets/hydrating-real.jpg','assets/hydrating-front-back.jpg','assets/hydrating-serum.jpg'],swatch:'#9ba7d1',concerns:['Dry / Dehydrated','Barrier Support'],ingredients:['Hyaluronic Acid','Ceramides','Trehalose'],step:'Treat',price:12},
  calming:{id:'calming',name:'Calming Serum',code:'CICA-BISA COMPLEX™ 20.31%',benefit:'Soothe + balance + comfort',desc:'A calming serum centered on a CICA-BISA COMPLEX™ approach, featuring Centella Complex, beta-glucan and bisabolol.',image:'assets/calming-real.jpg',gallery:['assets/calming-real.jpg','assets/calming-front-back.jpg','assets/calming-serum.jpg'],swatch:'#6aa99c',concerns:['Sensitive / Stressed','Redness Support'],ingredients:['Centella Complex','Beta-Glucan','Bisabolol'],step:'Treat',price:12},
  brightening:{id:'brightening',name:'Brightening Serum',code:'NIA-TXA COMPLEX™ 20.79%',benefit:'Brighten + even tone + glow',desc:'A brightening serum featuring a NIA-TXA COMPLEX™ concept with niacinamide, tranexamic acid, alpha-arbutin and vitamin C.',image:'assets/brightening-real.jpg',gallery:['assets/brightening-real.jpg','assets/brightening-front-back.jpg','assets/brightening-lifestyle.jpg','assets/brightening-detail.jpg'],swatch:'#e3b51f',concerns:['Dark Spots','Uneven Tone'],ingredients:['Niacinamide','Tranexamic Acid','Alpha-Arbutin','Vitamin C'],step:'Treat',price:12},
  clarifying:{id:'clarifying',name:'Clarifying Serum',code:'ACID COMPLEX™ 25.74%',benefit:'Clear + purify + refine',desc:'An acid-focused clarifying serum featuring mandelic acid, capryloyl salicylic acid (LHA) and betaine salicylate.',image:'assets/clarifying-real.jpg',gallery:['assets/clarifying-real.jpg','assets/clarifying-serum.jpg'],swatch:'#a46bd2',concerns:['Pores','Congestion / Excess Oil'],ingredients:['Mandelic Acid','LHA','Betaine Salicylate'],step:'Treat',price:12},
  rejuvenating:{id:'rejuvenating',name:'Rejuvenating Serum',code:'PGA-PEPTIDE COMPLEX™ 25.01%',benefit:'Firm + smooth + revitalize',desc:'A rejuvenation-focused serum featuring peptides, polyglutamic acid, acetyl hexapeptide-8 and adenosine.',image:'assets/rejuvenating-real.jpg',gallery:['assets/rejuvenating-real.jpg','assets/rejuvenating-serum.jpg','assets/pepti-lift-packaging.jpg'],swatch:'#d99a91',concerns:['Fine Lines','Loss of Firmness'],ingredients:['Peptides','Polyglutamic Acid','Acetyl Hexapeptide-8','Adenosine'],step:'Treat',price:12}
};
const CART_KEY='esencia_cart_v2';
const money=v=>`$${Number(v).toFixed(2)}`;
function getCart(){try{return JSON.parse(localStorage.getItem(CART_KEY)||'[]')}catch{return[]}}
function saveCart(cart){localStorage.setItem(CART_KEY,JSON.stringify(cart));updateBagCount()}
function cartSubtotal(){return getCart().reduce((s,x)=>s+(PRODUCTS[x.id]?.price||0)*x.qty,0)}
function updateBagCount(){const n=getCart().reduce((s,x)=>s+x.qty,0);document.querySelectorAll('[data-bag-count]').forEach(e=>e.textContent=n)}
function addToCart(id,qty=1){const p=PRODUCTS[id];if(!p)return;const cart=getCart();const row=cart.find(x=>x.id===id);if(row)row.qty+=qty;else cart.push({id,qty});saveCart(cart);openCart()}
function removeFromCart(id){saveCart(getCart().filter(x=>x.id!==id));renderCart()}
function renderCart(){
  const wrap=document.querySelector('[data-cart-items]');if(!wrap)return;
  const cart=getCart();
  const subtotal=cartSubtotal();
  const subtotalEl=document.querySelector('[data-cart-subtotal]'); if(subtotalEl) subtotalEl.textContent=money(subtotal);
  if(!cart.length){wrap.innerHTML='<div class="empty">Your bag is waiting for its first essential.</div>';document.querySelector('[data-cart-checkout]')?.classList.add('hide');return}
  document.querySelector('[data-cart-checkout]')?.classList.remove('hide');
  wrap.innerHTML=cart.map(x=>{const p=PRODUCTS[x.id];return `<div class="cart-item"><img src="${p.image}" alt="${p.name}"><div><h4>${p.name}</h4><p>${p.code}</p><p>Qty ${x.qty} · ${money(p.price)} each</p><button class="remove" onclick="removeFromCart('${p.id}')">Remove</button></div><strong>${money(p.price*x.qty)}</strong></div>`}).join('');
}
function openCart(){document.querySelector('[data-cart]')?.classList.add('open');renderCart()}
function closeCart(){document.querySelector('[data-cart]')?.classList.remove('open')}
function initCart(){updateBagCount();document.querySelectorAll('[data-open-cart]').forEach(b=>b.addEventListener('click',openCart));document.querySelector('[data-cart-overlay]')?.addEventListener('click',closeCart);document.querySelector('[data-cart-close]')?.addEventListener('click',closeCart);renderCart()}
function productCard(p){return `<article class="product-card"><div class="product-image" style="--accent:${p.swatch}"><a href="product.html?id=${p.id}" aria-label="View ${p.name}"><img src="${p.image}" alt="${p.name}"></a><span class="concern-pill">${p.concerns[0]}</span><button class="quick" type="button" onclick="addToCart('${p.id}')">Add to bag</button></div><div class="product-info"><div class="card-top"><div><div class="product-name">${p.name}</div><div class="product-code-mini">${p.code}</div></div><strong class="card-price">${money(p.price)}</strong></div><div class="product-sub"><span class="swatch" style="--swatch:${p.swatch}"></span>${p.benefit}</div><div class="card-meta"><span>30 ml / 1.01 fl. oz.</span><a href="product.html?id=${p.id}">Discover →</a></div></div></article>`}
function renderFeatured(){const el=document.querySelector('[data-featured]');if(el)el.innerHTML=Object.values(PRODUCTS).map(productCard).join('')}
function renderShop(){const grid=document.querySelector('[data-shop-grid]');if(!grid)return;let current='All';const buttons=document.querySelectorAll('[data-filter]');function draw(){const list=current==='All'?Object.values(PRODUCTS):Object.values(PRODUCTS).filter(p=>p.concerns.some(c=>c.includes(current)));grid.innerHTML=list.map(productCard).join('');const results=document.querySelector('[data-results]');if(results)results.textContent=`${list.length} ${list.length===1?'essential':'essentials'}`};buttons.forEach(b=>b.addEventListener('click',()=>{buttons.forEach(x=>x.classList.remove('active'));b.classList.add('active');current=b.dataset.filter;draw()}));draw()}
function initProduct(){const id=new URLSearchParams(location.search).get('id')||'hydrating';const p=PRODUCTS[id]||PRODUCTS.hydrating;const set=(sel,html)=>{const e=document.querySelector(sel);if(e)e.innerHTML=html};set('[data-product-title]',p.name);set('[data-product-code]',p.code);set('[data-product-benefit]',p.benefit);set('[data-product-desc]',p.desc);set('[data-product-price]',money(p.price));set('[data-product-ingredients]',p.ingredients.map(i=>`<span>${i}</span>`).join(''));set('[data-product-image]',`<img src="${p.gallery[0]}" alt="${p.name}">`);const thumbs=document.querySelector('[data-thumbs]');if(thumbs)thumbs.innerHTML=p.gallery.map((g,i)=>`<button class="thumb ${i===0?'active':''}" onclick="switchGallery('${g}',this)"><img src="${g}" alt="${p.name} view ${i+1}"></button>`).join('');const add=document.querySelector('[data-add-product]');if(add)add.onclick=()=>addToCart(p.id,Number(document.querySelector('[data-qty]')?.textContent||1));const minus=document.querySelector('[data-minus]'),plus=document.querySelector('[data-plus]'),q=document.querySelector('[data-qty]');minus?.addEventListener('click',()=>q.textContent=Math.max(1,+q.textContent-1));plus?.addEventListener('click',()=>q.textContent=+q.textContent+1);document.title=`${p.name} | ESEN’CIA`;document.querySelectorAll('[data-product-name]').forEach(e=>e.textContent=p.name);document.querySelectorAll('[data-product-benefit]').forEach(e=>e.textContent=p.benefit)}
function switchGallery(src,btn){document.querySelector('[data-product-image]').innerHTML=`<img src="${src}" alt="Product image">`;document.querySelectorAll('.thumb').forEach(x=>x.classList.remove('active'));btn.classList.add('active')}
const quizQuestions=[{q:'What does your skin need most right now?',a:['Deep hydration','Calm + comfort','Brighter, more even-looking tone','Clearer pores','Firmness + smoothness']},{q:'Which description feels closest?',a:['Tight or dehydrated','Sensitive or easily stressed','Dull or uneven-looking','Congested or oily','Fine lines or loss of firmness']},{q:'What kind of finish do you prefer?',a:['Plump + cushioned','Comforted + balanced','Fresh + luminous','Clean + refined','Smooth + supple']}];
function initQuiz(){const qEl=document.querySelector('[data-question]');if(!qEl)return;let step=0,answers=[];function draw(){const q=quizQuestions[step];qEl.innerHTML=`<div class="kicker">Question ${step+1} of ${quizQuestions.length}</div><h2 class="question">${q.q}</h2><div class="answers">${q.a.map((x,i)=>`<button class="answer ${answers[step]===i?'selected':''}" onclick="chooseAnswer(${i})">${x}</button>`).join('')}</div>`;document.querySelector('[data-progress]').style.width=`${((step+1)/quizQuestions.length)*100}%`;document.querySelector('[data-back]').disabled=step===0;document.querySelector('[data-next]').textContent=step===quizQuestions.length-1?'Reveal my serum':'Continue'}window.chooseAnswer=i=>{answers[step]=i;draw()};document.querySelector('[data-next]').onclick=()=>{if(answers[step]==null)return;if(step<quizQuestions.length-1){step++;draw()}else showResult()};document.querySelector('[data-back]').onclick=()=>{if(step>0){step--;draw()}};function showResult(){const counts={hydrating:0,calming:0,brightening:0,clarifying:0,rejuvenating:0};answers.forEach(i=>{counts[Object.keys(PRODUCTS)[i]]++});const id=Object.entries(counts).sort((a,b)=>b[1]-a[1])[0][0],p=PRODUCTS[id];document.querySelector('[data-quiz-card]').classList.add('hide');const r=document.querySelector('[data-result]');r.style.display='block';r.innerHTML=`<div class="kicker">Your essential balance</div><h2>${p.name}</h2><p>${p.benefit}. ${p.desc}</p><div class="result-card"><img src="${p.image}" alt="${p.name}"><div class="result-card-copy"><div class="card-price">${money(p.price)}</div><h3>${p.name}</h3><p>${p.ingredients.join(' · ')}</p><a class="btn" href="product.html?id=${p.id}">Explore your serum</a></div></div><a href="shop.html" class="text-link">View all five serums</a>`}draw()}
function initSearch(){const input=document.querySelector('[data-search-input]');const results=document.querySelector('[data-search-results]');if(!input||!results)return;input.addEventListener('input',()=>{const term=input.value.trim().toLowerCase();if(!term){results.innerHTML='';return}const list=Object.values(PRODUCTS).filter(p=>(p.name+' '+p.benefit+' '+p.ingredients.join(' ')+' '+p.concerns.join(' ')).toLowerCase().includes(term));results.innerHTML=list.length?list.map(p=>`<a href="product.html?id=${p.id}" class="search-result"><strong>${p.name}</strong><span>${p.benefit} · ${money(p.price)}</span></a>`).join(''):'<p style="color:#777">No essentials matched that search.</p>'})}
document.addEventListener('DOMContentLoaded',()=>{initCart();renderFeatured();renderShop();initProduct();initQuiz();initSearch()});
